### ISSUE TITLE
error of using sndfile

### ISSUE THREAD

**Issue by YongyuG** [dpirch/libfvad#9]
HI, 
Thanks for you works,
when I tried to compile the code, 
the error occured:
./configure: line 12008: syntax error near unexpected token `sndfile,'
./configure: line 12008: `  PKG_CHECK_MODULES(sndfile, sndfile)'

I have been install libsndfile1-dev already, but still happen,
this will cause the example can not be compiled as well,
Can you tell me how to fix this bug

Regards
Robin

**Comment by dpirch** [comment]
Apparently this happens if pkg-config was not installed when autoconf was run. If you have installed  libsndfile1-dev, pkg-config should have already been installed as a dependency, but you have to run `autoreconf -i` again to update the configure script. After that, `./configure` should work
